name: Deploy to AWS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli
      
      - name: Deploy Lambda with SAM
        run: |
          # Verify required files exist
          ls -la tools_data.json research_metadata.json templates/
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      
      - name: Deploy static assets to S3
        run: |
          aws s3 cp styles.css s3://dyscalculia-tools-187249759/
          aws s3 cp tools_data.json s3://dyscalculia-tools-187249759/
          aws s3 cp research_metadata.json s3://dyscalculia-tools-187249759/
          aws s3 cp favicon.ico s3://dyscalculia-tools-187249759/
          aws s3 cp favicon-32x32.png s3://dyscalculia-tools-187249759/
          aws s3 cp apple-touch-icon.png s3://dyscalculia-tools-187249759/
      
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id EMANNVI38BDCI --paths "/*"